### ISSUE TITLE
Needed use main.css in _diff/css directory

### ISSUE THREAD

**Issue by patsoftware** [marcoscv-work/madrid-theme#2]
I have a question about the nature of the necessity of using the main.css file in the _diffs/css directory ?.
Why you have overwrite the file main.,css instead of using only the file custom.css ?
Your use of the main.css file can not break functionalities that will be provided in future releases ?

Best regards

Antonio Patarozzi

**Comment by marcoscv-work** [comment]
You are right, actually I don't need add these lines in main.css:

@import url(dockbar-bubbles.css);
@import url(content.css);

There were some reasons to do this, but yes, we could move them to custom.css, to be clearest.

Working at Liferay I'm more aware about how I could break or not in future versions, I'm migrating my personal projects to Liferay 7 and main.css doesn't have any similarity.

If you want to do some smoke test over changes between custom.css and main.css and then send me a pull request, it would be perfect.

Thank you so much! ;)
