### ISSUE TITLE
which is the name of portlets thumbnails?

### ISSUE THREAD

**Issue by sergiormb** [marcoscv-work/madrid-theme#5]
I have seen on the thumbnails that there is a portlet with pictures or videos, which is the name of them? as I can install?

Regards

**Comment by marcoscv-work** [comment]
hi!

Each time you install a theme a site template is crated here:

[image: Imágenes integradas 1]

Control panel > site templates > Madrid Theme

:D

2016-10-25 14:06 GMT+02:00 Sergio Pino Márquez notifications@github.com:

**Comment by sergiormb** [comment]
Perdón, también soy español, creo que no he traducido bien :D
Me refiero a las imágenes que aparecen en tus capturas, es un slider creo. Son portlets o lo has creado a mano?

Un saludo y gran trabajo :D

**Comment by marcoscv-work** [comment]
Buenas!

Gracias!

Es una estructura y plantilla, para verlo en directo es mejor que lo veas
por ti mismo en el site template.

Saludos,
Marcos.

2016-10-25 20:55 GMT+02:00 Sergio Pino Márquez notifications@github.com:
