### ISSUE TITLE
container size

### ISSUE THREAD

**Issue by bgdaniels** [marcoscv-work/madrid-theme#7]
Longtime since I've interacted with you :-) I want to change the container size on madrid to be 979, but for the life of me, can't seem to find how you set the container size. Could you point me in the right direction? BTW, love your LR 7 themes. However, none of the themes layout well for ecommerce.
thanks for your help.

**Comment by marcoscv-work** [comment]
I think I'm using bootstrap default containers so in this way you should change .container and container-fluid classes to set them to your needs.

Let me know if this works.
